version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    container_name: "app-starter-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-starter
    volumes:
      - "app-starter-data:/var/lib/postgresql/data"

volumes:
  app-starter-data:
